"""initial models

Revision ID: 89e09fec65b1
Revises: d39f956bf8fc
Create Date: 2025-07-11 18:02:40.864048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e09fec65b1'
down_revision = 'd39f956bf8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_report')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.VARCHAR(length=7), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('attendance_percent', sa.FLOAT(), nullable=True),
    sa.Column('avg_homework', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
